export * from './checkValid'
export * from './touchAll'
export * from './uuid'
export * from './runValidators'
export * from './validateField'
export * from './validateAllFields'
export * from './getValues'
export * from './getErrors'
export * from './last'
export * from './getFormStateKey'

export const isNative = typeof navigator != 'undefined' && navigator.product == 'ReactNative'
